name: "Hit a webhook"
 
on:
  push:
    tags:
      - '**'
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        curl -X GET "https://salasakahiji.azurewebsites.net/api/syncToday?segmentId=34705519&forceUpdate=true"
